const express = require('express');
const healthController = require('../controllers/health');
const notesRouter = require('./notes');
const swaggerSpec = require('../../swagger');

const router = express.Router();
// Health endpoint

/**
 * @swagger
 * /:
 *   get:
 *     summary: Health endpoint
 *     responses:
 *       200:
 *         description: Service health check passed
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 status:
 *                   type: string
 *                   example: ok
 *                 message:
 *                   type: string
 *                   example: Service is healthy
 *                 timestamp:
 *                   type: string
 *                   format: date-time
 *                 environment:
 *                   type: string
 *                   example: development
 */
router.get('/', healthController.check.bind(healthController));

/**
 * PUBLIC_INTERFACE
 * GET /openapi.json
 * Serve the current OpenAPI spec JSON generated by swagger-jsdoc.
 * This reuses the central swagger configuration and keeps /docs intact.
 */
router.get('/openapi.json', (req, res) => {
  // Optionally ensure correct content-type
  res.type('application/json').status(200).send(swaggerSpec);
});

// Notes routes
router.use('/api/notes', notesRouter);

module.exports = router;
